export const categories = [
  "Books",
  "Design",
  "Fashion & Beauty",
  "Food",
  "Performing Arts",
  "Visual Arts",
  "Careers",
  "Entrepreneurship",
  "Investing",
  "Management",
  "Marketing",
  "Non-Profit",
  "Comedy Interviews",
  "Improv",
  "Stand-Up",
  "Courses",
  "How To",
  "Language Learning",
  "Self-Improvement",
  "Comedy Fiction",
  "Drama",
  "Science Fiction",
  "Government",
  "History",
  "Alternative Health",
  "Fitness",
  "Medicine",
  "Mental Health",
  "Nutrition",
  "Sexuality",
  "Education for Kids",
  "Parenting",
  "Pets & Animals",
  "Stories for Kids",
  "Animation & Manga",
  "Automotive",
  "Aviation",
  "Crafts",
  "Games",
  "Hobbies",
  "Home & Garden",
  "Video Games",
  "Music Commentary",
  "Music History",
  "Music Interviews",
  "Business News",
  "Daily News",
  "Entertainment News",
  "News Commentary",
  "Politics",
  "Sports News",
  "Tech News",
  "Buddhism",
  "Christianity",
  "Hinduism",
  "Islam",
  "Judaism",
  "Religion",
  "Spirituality",
  "Astronomy",
  "Chemistry",
  "Earth Sciences",
  "Life Sciences",
  "Mathematics",
  "Natural Sciences",
  "Nature",
  "Physics",
  "Social Sciences",
  "Documentary",
  "Personal Journals",
  "Philosophy",
  "Places & Travel",
  "Relationships",
  "Baseball",
  "Basketball",
  "Cricket",
  "Fantasy Sports",
  "Football",
  "Golf",
  "Hockey",
  "Rugby",
  "Running",
  "Soccer",
  "Swimming",
  "Tennis",
  "Volleyball",
  "Wilderness",
  "Wrestling",
  "Technology",
  "True Crime",
  "After Shows",
  "Film History",
  "Film Interviews",
  "Film Reviews",
  "TV Reviews",
];
